#!/usr/bin/env ruby

# start-rubyci - build start script
#
# Copyright (C) 2005-2013 Tanaka Akira  <akr@fsij.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#  3. The name of the author may not be used to endorse or promote
#     products derived from this software without specific prior
#     written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

$:.unshift File.dirname(File.expand_path(__FILE__))

require 'chkbuild'

#ENV['LC_ALL'] = 'C'

# resource limits
#word_bytes = [nil].pack("p").length
#ChkBuild.limit(:cpu => 3600*4) # seconds
#ChkBuild.limit(:stack => 1024*1024*10*word_bytes) # bytes
#ChkBuild.limit(:data => 1024*1024*500*word_bytes) # bytes
#ChkBuild.limit(:as => 1024*1024*500*word_bytes) # bytes

# process priority
#ChkBuild.nice = 10

# ChkBuild.nickname identify chkbuild installation.
# It is used for title of HTML, etc.
# The default is the hostname (without domain).
# ChkBuild.nickname = 'nickname'

ChkBuild.nickname = ENV["RUBYCI_NICKNAME"] if ENV["RUBYCI_NICKNAME"]

# ChkBuild.top_uri is used for RSS.
# ChkBuild.top_uri = "file://#{ChkBuild.public_top}/"
# ChkBuild.top_uri = nil # use relative URL

#ChkBuild.azure_upload_target rescue nil
ChkBuild.s3_upload_target
arg = [].push(
  [
    { :suffix_? => 'master', :output_interval_timeout => '20min' },
    *ChkBuild::Ruby.maintained_release_branches
  ],

#   [ # :abi_check needs --enable-shared
#     { :suffix_? => 'trunk', :abi_check_notitle => '/home/akr/ruby/200p0', :output_interval_timeout => '10min' },
#     { :suffix_? => '2.1', :abi_check => '/home/akr/ruby/210p0' },
#     { :suffix_? => '2.0.0', :abi_check => '/home/akr/ruby/200p0' },
#     { :suffix_? => '1.9.3', :abi_check => '/home/akr/ruby/193p0', :abi_check_options => ['--skip-symbols', ChkBuild::SAMPLE_DIRECTORY+'abi-check-ruby-1.9.3-skip-symbols.txt'] },
#   ],

  # ChkBuild::Ruby::MaintainedBranches,
  # %w[trunk],
  # %w[trunk 2.0.0],

  # ['o0', 'o1', nil, 'o3', 'os'],

  [nil, "pth"],

  # ['m32', 'm64'],

  # [nil, { :suffix_? => "-outofplace", :inplace_build => false}]

  # :git_shallow_clone => true,
  # :autoconf_command => 'autoconf',
  # :configure_args_valgrind => %w[--with-valgrind],
  # :configure_args_enable_shared => %w[--enable-shared],
  # :cppflags => %w[-DRUBY_DEBUG_ENV],
  # :optflags => %w[-O2],
  # :debugflags => %w[-g],
  # :warnflags => %w[-W -Wall -Wformat=2 -Wundef -Wno-parentheses -Wno-unused-parameter -Wno-missing-field-initializers],
  # :dldflags => %w[],

  # :validate_dependencies => false,
  # :validate_dependencies => true,     # needs gmake and gcc 4.5 or later.
  #
  # :do_test => true,

  # :old => 1,

  :timeout => '2h',

  :output_interval_timeout => '5min'
  )

h = arg[-1]

case uname = `uname -srm`
when /\ALinux/
  ENV['HOME'] = "/home/#{ENV['USER']}" if File.exist?('/etc/redhat-release')
  h[:optflags] = '-O3 -mfpmath=sse -msse2' if /i.86/ =~ uname
when /\AFreeBSD/
  ENV['PATH'] = "#{ENV['PATH']}:/usr/local/bin"
  h[:configure_args_with_opt_dir] = %w[--with-opt-dir=/usr/local]
  h[:optflags] = '-O3 -mfpmath=sse -msse2' if /i.86/ =~ uname
when /\ASunOS/
  h[:configure_args_disable_werror] = %w[--disable-werror]
#  h[:configure_args_cc] = %w[CC=/opt/solarisstudio12.4/bin/cc]
  arg[0].slice!(1,9)
  h[:optflags] = '-O3 -mfpmath=sse -msse2' if /i86/ =~ uname
  h[:git_shallow_clone] = true
end

case ChkBuild.nickname
when 'tk2-243-31075', 'armv8b'
  arg[0].slice!(1,9)
when 'arch'
  h[:autoreconf_command] = 'autoreconf'
when 'archlinux'
  h[:configure_args_cc] = %w[CC=clang]
  ENV['RUBY_FORCE_TEST_JIT'] = '1'
when 'scw-9d6766'
  arg[0].slice!(1,9)
  h[:timeout] = '3h'
when 'openbsd-current'
  h[:autoconf_command] = 'autoconf-2.69'
  h[:autoreconf_command] = 'autoreconf-2.69'
  h[:configure_args_opt] = %w[--with-opt-dir=/usr/local]
  arg[0][0][:output_interval_timeout] = '60min'
  ENV['RUBY_FIBER_VM_STACK_SIZE'] = '32768'
  ENV['RUBY_FIBER_MACHINE_STACK_SIZE'] = '65536'
  h[:git_shallow_clone] = true
when 'freebsd12'
  h[:configure_args_with_opt_dir] = %w[--with-opt-dir=/usr/local]
when 'amazon'
  h[:timeout] = '4h'
  h[:output_interval_timeout] = '5min'
when 'icc-x64'
  ENV["CC"] = "icc -std=gnu99"
  ENV["CXX"] = "icpc -std=gnu++11"
  h[:output_interval_timeout] = '20min'
when 'centos7'
  h[:cppflags] ||= []
  # GCC is very old and buggy in CentOS7.  This is needed to disable the false positive warning:
  # https://rubyci.org/logs/rubyci.s3.amazonaws.com/centos7/ruby-master/log/20200512T153002Z.log.html.gz
  #
  #   eval.c:577:17: warning: ‘file’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  #        const char *file = rb_source_location_cstr(&line);
  h[:cppflags] << "-Wno-maybe-uninitialized"
when /\Aandroid\d+-/
  arg[0].slice!(1,9)
  h[:git_shallow_clone] = true
  # hardlink is not available for a normal user on Android
  def File.link(new, old); end
  h[:autoreconf_command] = 'autoreconf'
when /^solaris/ # F
  ENV["MAKE"] = "gmake"
  ENV["RUBY_TEST_TIMEOUT_SCALE"] = "10" if ChkBuild.nickname =~ /sunc$/
  h[:timeout] = '5h'
  if ChkBuild.nickname =~ /^solaris10/
    h[:configure_args_disable_largefile] = %w[--disable-largefile]
    h[:configure_args_disable_werror] = %w[--disable-werror] # needed?
    ENV["PKG_CONFIG"] = "/opt/csw/bin/pkg-config" # system's pkg-config is too old
    if ChkBuild.nickname == "solaris10-gcc"
      ENV["CC"] = "/opt/csw/bin/gcc"
    else # solaris10-sunc
      ENV["CC"] = "cc"
      # Open Solaris Studio's cc (sunc) does not record the rpath of OpenCSW's
      # libssl.so to the executable, so explicitly specify the rpath
      ENV["LDFLAGS"] = "-R/opt/csw/lib"
    end
  else
    if ChkBuild.nickname == "solaris11-gcc"
      ENV["PKG_CONFIG_PATH"] = "/usr/lib/64/pkgconfig"
      ENV["CC"] = "/usr/gcc/9/bin/gcc"
    end
  end
when "raspbian10-aarch64"
  ENV["RUBY_TEST_TIMEOUT_SCALE"] = "3"
when "debian-riscv64"
  arg[0].slice!(1,9)
when "osx1013", "osx1015", "osx1100arm"
  h[:autoreconf_command] = 'autoreconf'
  ENV["PATH"] = "/opt/local/bin:/opt/local/sbin:#{ENV['PATH']}"
  h[:configure_args_with_openssl_dir] = %w[--with-openssl-dir=/opt/local]
end

autoconf_command = '/home/naruse/local/autoconf/bin/autoconf'
h[:autoconf_command] = autoconf_command if File.exist?(autoconf_command)

autoreconf_command = '/home/naruse/local/autoconf/bin/autoreconf'
h[:autoreconf_command] = autoreconf_command if File.exist?(autoreconf_command)

h[:configure_args] = ["--with-baseruby=#{RbConfig.ruby}"]

ChkBuild::Ruby.def_target(*arg)

ChkBuild.main
