#!/usr/bin/env ruby

require 'build'
require 'chkbuild/ruby'

Build.limit(:data=>1024*1024*600, :as=>1024*1024*600)

GCC = Build.def_perm_target("gcc",
  ["trunk", "4.1", "4.0"],
  :old => 1) {|b, suffix|
  gcc_dir = b.work_dir
  gcc_branch = {
    "trunk"=>"trunk",
    "4.1"=>"branches/gcc-4_1-branch",
    "4.0"=>"branches/gcc-4_0-branch"
  }[suffix]
  Dir.chdir("..") {
    b.svn("svn://gcc.gnu.org/svn/gcc/#{gcc_branch}", 'gcc')
  }
  b.mkcd("objdir")
  b.run("../../gcc/configure", "--prefix=#{gcc_dir}", "--enable-languages=c", "--disable-shared", "--disable-multilib")
  b.make("bootstrap", "install", :timeout=>'5h')
  b.run("#{gcc_dir}/bin/gcc", '-v') {|bb, log|
    if /^gcc version (.*)$/ =~ log
      b.update_title(:version, "gcc #{$1}")
    end
  }
}

def_build_ruby2(
  ["trunk", "1.8"],
  [nil, "o3"],
  [nil, "pth"],
  GCC,
  :old => 1)

Build.main
