#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.limit(:data=>1024*1024*800, :as=>1024*1024*800)

ChkBuild::Ruby.def_target(
  ChkBuild::Ruby::MaintainedBranches, # 'trunk',
  # ['m32', 'm64'],
  [nil, "pth"],
  :old => 1)

ChkBuild.main
