#!/usr/bin/env ruby

require 'build'

Build.limit(:data=>1024*1024*300, :as=>1024*1024*300)

Build.perm_target("yarv") {|b|
  ruby_curr_dir = b.work_dir
  Dir.chdir("..") {
    Build.svn("http://www.atdot.net/svn/yarv/trunk", 'yarv')
    Dir.chdir("yarv") {
      Build.run("autoconf")
    }
  }
  Build.mkcd("yarv")
  Build.run("../../yarv/configure", "--prefix=#{ruby_curr_dir}") {|log|
    if /^checking target system type\.\.\. (\S+)$/ =~ log
      Build.update_title(:version, "yarv #{$1}")
    end
  }
  Build.add_finish_hook {
    log = Build.all_log
    mark = ''
    mark << "[BUG]" if /\[BUG\]/i =~ log
    mark << "[SEGV]" if /segmentation fault|signal segv/i =~
      log.sub(/combination may cause frequent hang or segmentation fault/, '') # skip tk message.
    mark << "[FATAL]" if /\[FATAL\]/i =~ log
    Build.update_title(:mark, mark)
  }
  Build.make(:rlimit_data=>1024*1024*200, :rlimit_as=>1024*1024*200)
  Build.run("./ruby", "-v") {|log|
    if /^ruby [0-9.]+ \([0-9\-]+\) \[\S+\]$/ =~ log
      Build.update_title(:version, $&)
    end
  }
  Build.make("install-nodoc")
  Build.run("./ruby", "../../yarv/sample/test.rb", :reason=>"test.rb")
  Build.run("./ruby", "../../yarv/test/runner.rb", "-v", :reason=>"test-all") {|log|
    if /^\d+ tests, \d+ assertions, (\d+) failures, (\d+) errors$/ =~ log
      failures = $1.to_i
      errors = $2.to_i
      if failures != 0 || errors != 0
        Build.update_title(:status, "#{failures}F#{errors}E")
      end
    end
  }
}
