#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.limit(:data=>1024*1024*800, :as=>1024*1024*800)

ChkBuild::Ruby.def_target(
  ChkBuild::Ruby::MaintainedBranches,
  [nil, "pth"],
  :separated_srcdir => true)

ChkBuild.main
