#!/usr/bin/env ruby

require 'build'
require 'chkbuild/ruby'

Build.limit(:data=>1024*1024*300, :as=>1024*1024*300)

def modify_file(filename)
  content = yield File.read(filename)
  open(filename, "w") {|f|
    f.print content
  }
end

Autoconf = Build.def_target("autoconf") {|b|
  dir = b.work_dir
  Dir.chdir("..") {
    b.gnu_savannah_cvs('autoconf', 'autoconf', nil)
  }
  b.mkcd("objdir")
  b.run("../../autoconf/configure", "--prefix=#{dir}")
  # modify Makefile to not use help2man.
  modify_file("Makefile") {|content|
    content.sub(/^SUBDIRS\s*=.*$/) { $&.sub(/ man /, ' ') }
  }
  b.make
  b.make("install")

  b.run("#{dir}/bin/autoconf", '--version', :section=>'version')
}

Autoconf.add_title_hook('version') {|title, log|
  case log
  when /^Autoconf version (.*)$/
    title.update_title(:version, "autoconf #{$1}")
  when /^autoconf \(GNU Autoconf\) (.*)$/
    title.update_title(:version, "autoconf #{$1}")
  end
}

def_build_ruby(
  ["trunk", "1.8"],
  Autoconf,
  :separated_srcdir => true)

Build.main
