#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.limit(:data=>1024*1024*300, :as=>1024*1024*300)

ChkBuild::Ruby.def_target(
  ["trunk", "half-baked-1.9", "1.8"],
  [nil, "pth"],
  :separated_srcdir => true)

ChkBuild.main
