#!/usr/bin/env ruby

require 'build'
require 'chkbuild/ruby'

#Build.rsync_ssh_upload_target("akr2@localhost::serein-localhost-upload")

Build.limit(:data=>1024*1024*300, :as=>1024*1024*300)

build_ruby(
  ["trunk", "1.8"],
  [nil, "pth"])


=begin
  ["trunk", [], "", nil],
  ["1.8", [], "", "ruby_1_8"],
  ["trunk-pth", %w{--enable-pthread}, "", nil],
  ["1.8-pth", %w{--enable-pthread}, "", "ruby_1_8"])
=end
