#!/usr/bin/env ruby

require 'build'

COMBFAIL1 = Build.def_target("combfail1",
  ["succ", "fail"]) {|b, suffix|
  case suffix
  when "succ" then command = "true"
  when "fail" then command = "false"
  end
  b.run(command)
}

Build.def_target("combfail2", COMBFAIL1) {|b, cf1|
  combfail2_dir = b.work_dir
  /\Acombfail1=/ =~ cf1
  combfail1_dir = $'
  b.run(*%W(echo #{combfail1_dir} #{combfail2_dir}))
}

Build.main
