#!/usr/bin/env ruby

require 'chkbuild'

t = ChkBuild.def_target("fmesg") {|b|
  b.run("echo", "this fails")
  if /this fails/ =~ b.logfile.get_section('echo')
    raise ChkBuild::Build::CommandError.new(0, "echo")
  end
}

t.add_failure_hook('echo') {|log|
  'FAIL'
}

ChkBuild.main
