#!/usr/bin/env ruby

require 'chkbuild'

#ChkBuild.limit(:data=>1024*1024*2000, :as=>1024*1024*2000)

ChkBuild.def_target("svnruby") {|b|
  b.svn("http://svn.ruby-lang.org/repos/ruby", 'trunk', 'ruby')
}

ChkBuild.main
