#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.def_target("warn") {|b|
  b.run("echo", "warn")
}

ChkBuild.define_title_hook('warn', 'echo') {|title, log|
  title.update_title(:version, "foo") 
}

ChkBuild.main
