#!/usr/bin/env ruby

require 'chkbuild'

warn = ChkBuild.def_target("warn") {|b|
  b.run("echo", "warn")
}

warn.add_title_hook('echo') {|title, log|
  title.update_title(:version, "foo") 
}

ChkBuild.main
