#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.def_target('git') {|b|
  opts = {:shared_gitdir=>ChkBuild.build_top}
  b.git('git://github.com/rubyspec/rubyspec.git', 'tst-rubyspec2', opts)
}

ChkBuild.main
