#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.def_target("opts",
  [
    {:suffix_1 => "a", :foo=>"a", :bar=>"x"},
    {:suffix_1 => "b", :foo=>"b", :bar=>"y"}
  ],
  :bar=>"z",
  :baz=>"A") {|b|
  pp b.opts
}

ChkBuild.main
