#!/usr/bin/env ruby

require 'build'

ChkBuild.add_upload_hook {|name|
  p "#{ChkBuild.public_top}/#{name}"
}

ChkBuild.def_target("uptest", ["dev", "stable"]) {|b,|
  b.run("echo", "uptest")
}

ChkBuild.main
