#!/usr/bin/env ruby

require 'build'

gcc_v = Build.def_target("gcc-v") {|b|
  b.run("gcc", '-v', :section=>'version')
}

gcc_v.add_title_hook('version') {|title, log|
  if /^gcc version (.*)$/ =~ log
    title.update_title(:gcc_version, "(gcc #{$1})")
  end
}

ChkBuild.main
