#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.def_target("coretest") {|b|
  FileUtils.cp(`which ruby`.chomp, "ruby")
  b.run("./ruby", "-e", <<'End')
Process.setrlimit(Process::RLIMIT_CORE, Process::RLIM_INFINITY, Process::RLIM_INFINITY)
trap("SEGV", "DEFAULT")
Process.kill("SEGV", $$)
End
}

ChkBuild.main
