#!/usr/bin/env ruby

require 'build'

Build.target("failure") {|curr_dir|
  Build.add_finish_hook {
    log = Build.all_log
    mark = ''
    mark << "[BUG]" if /\[BUG\]/i =~ log
    mark << "[SEGV]" if /Segmentation fault/i =~ log
    mark << "[FATAL]" if /\[FATAL\]/i =~ log
    Build.update_title(:mark, mark)
  }
  Build.run("echo", "[bug]")
  Build.run("false")
}
