#!/usr/bin/env ruby

require 'build'

Build.add_upload_hook {|name|
  p "#{Build.public_dir}/#{name}"
}

Build.def_perm_target("uptest", ["dev", "stable"]) {|b|
  b.run("echo", "uptest")
}

Build.main
