#!/usr/bin/env ruby

require 'build'

Dep1 = Build.def_perm_target("lib1", ["dev", "stable"]) {|b|
}

Dep2 = Build.def_perm_target("lib2", ["dev", "stable"]) {|b|
}

Build.def_perm_target("app", ["dev", "stable"], Dep1, Dep2) {|b, suffix, lib1, lib2|
}

Build.main
