#!/usr/bin/env ruby

require 'chkbuild'

def coredump(b)
  b.run("./ruby", "-e", <<'End')
Process.setrlimit(Process::RLIMIT_CORE, Process::RLIM_INFINITY, Process::RLIM_INFINITY)
trap("SEGV", "DEFAULT")
Process.kill("SEGV", $$)
End
end

ChkBuild.def_target("core2test") {|b|
  FileUtils.cp(`which ruby`.chomp, "ruby")
  b.catch_error { coredump(b) }
  b.catch_error { coredump(b) }
}

ChkBuild.main
