#!/usr/bin/env ruby

require 'chkbuild'

#ChkBuild.limit(:data=>1024*1024*2000, :as=>1024*1024*2000)

ChkBuild.def_target("gitcheckout") {|b|
  b.git('git://github.com/akr/depq.git', 'depq-work', {})
}

ChkBuild.main
