#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.def_target("opts",
  [
    ["a", {:foo=>"a", :bar=>"x"}],
    ["b", {:foo=>"b", :bar=>"y"}]
  ],
  :bar=>"z",
  :baz=>"A") {|b|
  pp b.opts
}

ChkBuild.main
