#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.def_target("networkerror") {|b|
  b.network_access {
    if rand < 0.5
      b.run("false")
    else
      b.run("true")
    end
  }
  b.run("true")
}

ChkBuild.main
