#!/usr/bin/env ruby

require 'chkbuild'

Dep1 = ChkBuild.def_target("dep1",
  ["dev", "stable"]) {|b, suffix|
  b.catch_error { raise "foo error" }
}

ChkBuild.def_target("dep2",
  ["dev", "stable"],
  Dep1) {
    |b, suffix, dep1|
  p b.suffixed_name
}

ChkBuild.main
