#!/usr/bin/env ruby

require 'build'

Build.target("coretest") {|curr_dir|
  FileUtils.cp(`which ruby`.chomp, "ruby")
  Build.run("./ruby", "-e", <<'End')
Process.setrlimit(Process::RLIMIT_CORE, Process::RLIM_INFINITY, Process::RLIM_INFINITY)
trap("SEGV", "DEFAULT")
Process.kill("SEGV", $$)
End
}
