#!/usr/bin/env ruby

require 'chkbuild'

Dep1 = ChkBuild.def_target("dep1",
  ["dev", "stable"]) {|b|
  b.catch_error { raise "foo error" }
  Dir.mkdir('bin')
}

ChkBuild.def_target("dep2",
  ["dev", "stable"],
  Dep1) {|b|
  p b.suffixes
  p b.depbuilds
  p b.suffixed_name
  b.run('env')
}

ChkBuild.main
