#!/usr/bin/env ruby

require 'chkbuild'

#ChkBuild.limit(:data=>1024*1024*2000, :as=>1024*1024*2000)

ChkBuild.def_target("randomerror") {|b|
  b.network_access {
    if rand < 0.5
      b.run("false")
    else
      b.run("true")
    end
  }
  if rand < 0.5
    b.run("false")
  else
    b.run("true")
  end
}

ChkBuild.main
