#!/usr/bin/env ruby

require 'chkbuild'

ChkBuild.def_target("savannah") {|b|
  b.gnu_savannah_cvs('config', 'config', nil)
  b.run("config/config.guess")
}

ChkBuild.define_title_hook('savannah', 'config.guess') {|title, log|
  title.update_title(:statusex, log.chomp[/[^\n]*\z/])
}

ChkBuild.main
