#!/usr/bin/env ruby

require 'build'

Build.def_perm_target("failure") {|b|
  b.add_finish_hook {
    log = b.all_log
    mark = ''
    mark << "[BUG]" if /\[BUG\]/i =~ log
    mark << "[SEGV]" if /Segmentation fault/i =~ log
    mark << "[FATAL]" if /\[FATAL\]/i =~ log
    b.update_title(:mark, mark)
  }
  b.run("echo", "[bug]")
  b.run("false")
}

Build.main
