#!/usr/bin/env ruby

require 'build'

Build.perm_target("gcc-v") {|b|
  Build.run("gcc", '-v') {|log|
    if /^gcc version (.*)$/ =~ log
      Build.update_title(:gcc_version, "(gcc #{$1})")
    end
  }
}
